
### login user
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "userDetails": {
        "email": "carmeltest@gmail.com",
        "password": "testpassword"
    }
}

### Register user
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "userDetails": {
        "name": "testuser",
        "password": "testpassword",
        "email": "carmeltest@gmail.com",
        "birthDate":"01/01/2002"
    }
    
}

### login handler
POST http://localhost:3000/login
Content-Type: application/json


### create playlist
POST http://localhost:3000/musicalAIConsultant/createPlaylist
Content-Type: application/json
Cookie: spotify_access_token=BQBBSiKOyRi8zWfzJ5cAh8A7FRMtTScbiNSktpWy2nHH-Vry0VQCpeQfn313KQfslxca3ojn21tiZ9-F7k7cx4V_50teipCBDFezFlZvboMADrSY0uxWc187vS8lMbTNNaEDFov00TWxxAh1Bo9fA0iWEXqEUlu5lsJk-VKNfgeLFoqziKwJkPJjMhci9SEyUzct5JbMwAjJXSJ0pwPETu-ocL_7tAkk0j5wB3GiNc1tBy1u9hi831QsOY4wP-3Z_wcAZ9dXIFZDWM-XERkvsySNr-9yDyBu8Xf0mQ4AjdE; spotify_refresh_token=AQA0tVe82jULMCxMIPz_JlbfvJsGOdmcwVVU-VGUVNl656rj5o3nFAWZu-lhj6OT_ZvHikzXPFEDw8HlxlWx_fLu8Y6SV0Arm8DGa_l3CH52Km5c8-HZSo7p9B23aQYdjQw

{
    "vibe": "calm",
    "activity": "road trip"
}